---
- name: Install Podman
  hosts: centos
  become: yes
  tasks:
    - name: update cache
      yum: update_cache=yes
    - name: Install Podman
      package:
        name: "podman"
        state: present
    - name: Install Docker
      package:
        name: "docker"
        state: present
    - name: Remove pip podman compose 
      pip:
        name: podman-compose
        state: absent
    - name: Install podman-compose via git
      shell: curl -o /usr/local/bin/podman-compose https://raw.githubusercontent.com/containers/podman-compose/devel/podman_compose.py
      args:
        warn: no
    - name: chmod permissions of file
      shell: chmod +x /usr/local/bin/podman-compose
    - name: Install docker-compose
      pip:
        name: "docker-compose"
