---
- hosts: "{{ select_hosts }}"
  tasks:
    - name: update cache
      yum: update_cache=yes
    - block:
        - name: Install setools
          package:
            name: "setools"
            state: present
        - name: Install python3-libselinux
          package:
            name: "python3-libselinux"
            state: present
        - name: Install python36
          package:
            name: "python36"
            state: present
      rescue:
        - name: (RESCUE) Install python3
          package:
            name: "python3"
            state: present
      become: true
    - block:
        - name: pip3 install selinux
          ansible.builtin.pip:
            name: selinux
            executable: pip3
            extra_args: --user
            state: present
      rescue:
        - block:
            - name: (RESCUE) pip install selinux
              ansible.builtin.pip:
                name: selinux
                extra_args: --user
                state: present
          rescue:
            - name: (RESCUE) executable pip install selinux
              ansible.builtin.pip:
                name: selinux
                executable: pip
                extra_args: --user
                state: present
      always:
        - name: Set SELinux to Permissive mode
          ansible.posix.selinux:
            policy: targeted
            state: permissive
          become: true
