---
- name: Install sysstat
  hosts: "{{ select_hosts }}"
  become: yes
  tasks:
    - name: update cache
      yum: update_cache=yes
    - name: Install sysstat
      package:
        name: "sysstat"
        state: present


